#include <sibir_impl.hpp>
#include "sibir.h"
#include <dlfcn.h>
#include <functional>
#include <hip/amd_detail/hip_prof_str.h>
#include <iostream>
#include <map>


Sibir* Sibir::sibir_;

void __attribute__((constructor)) Sibir::init() {
    puts("Initializing Sibir.\n");
    sibir_ = new Sibir();
    sibir_->recordAllOriginalHipSymbols();
    // Call to user instrumented code
    sibir_at_init();
}

__attribute__((destructor)) void Sibir::destroy() {
    delete sibir_;
    sibir_at_term();
    puts("Terminating Sibir.\n");
}

void Sibir::recordAllOriginalHipSymbols() {
    for (int i = hip_api_id_t::HIP_API_ID_FIRST; i != hip_api_id_t::HIP_API_ID_LAST; i++) {
        auto api_name = hip_api_name(i);
        if (strcmp(api_name, "unknown") != 0) {
            recordOriginalHipSymbol(hip_api_name(i));
        }
    }
    recordOriginalHipSymbol("__hipGetPCH");
    recordOriginalHipSymbol("__hipPopCallConfiguration");
    recordOriginalHipSymbol("__hipPushCallConfiguration");
    recordOriginalHipSymbol("__hipRegisterFatBinary");
    recordOriginalHipSymbol("__hipRegisterFunction");
    recordOriginalHipSymbol("__hipRegisterManagedVar");
    recordOriginalHipSymbol("__hipRegisterSurface");
    recordOriginalHipSymbol("__hipRegisterTexture");
    recordOriginalHipSymbol("__hipRegisterVar");
    recordOriginalHipSymbol("__hipUnregisterFatBinary");
}

void Sibir::recordOriginalHipSymbol(const char* sym) {
    void*originalSymbol = dlsym(RTLD_NEXT, sym);
    if (originalSymbol == nullptr)
        std::cout << "Failed to capture symbol " + std::string(sym) + "\n";
    originalHipSymbols_[sym] = originalSymbol;
}

Sibir& Sibir::getInstance() {
    if (sibir_ == nullptr)
        Sibir::init();
    return *sibir_;
}

//HIP_API_ID___hipPopCallConfiguration = 1,
//    HIP_API_ID___hipPushCallConfiguration = 2,
//    HIP_API_ID_hipArray3DCreate = 3,
//    HIP_API_ID_hipArrayCreate = 4,
//    HIP_API_ID_hipArrayDestroy = 5,
//    HIP_API_ID_hipChooseDevice = 6,
//    HIP_API_ID_hipConfigureCall = 7,
//    HIP_API_ID_hipCtxCreate = 8,
//    HIP_API_ID_hipCtxDestroy = 9,
//    HIP_API_ID_hipCtxDisablePeerAccess = 10,
//    HIP_API_ID_hipCtxEnablePeerAccess = 11,
//    HIP_API_ID_hipCtxGetApiVersion = 12,
//    HIP_API_ID_hipCtxGetCacheConfig = 13,
//    HIP_API_ID_hipCtxGetCurrent = 14,
//    HIP_API_ID_hipCtxGetDevice = 15,
//    HIP_API_ID_hipCtxGetFlags = 16,
//    HIP_API_ID_hipCtxGetSharedMemConfig = 17,
//    HIP_API_ID_hipCtxPopCurrent = 18,
//    HIP_API_ID_hipCtxPushCurrent = 19,
//    HIP_API_ID_hipCtxSetCacheConfig = 20,
//    HIP_API_ID_hipCtxSetCurrent = 21,
//    HIP_API_ID_hipCtxSetSharedMemConfig = 22,
//    HIP_API_ID_hipCtxSynchronize = 23,
//    HIP_API_ID_hipDestroyExternalMemory = 24,
//    HIP_API_ID_hipDestroyExternalSemaphore = 25,
//    HIP_API_ID_hipDeviceCanAccessPeer = 26,
//    HIP_API_ID_hipDeviceComputeCapability = 27,
//    HIP_API_ID_hipDeviceDisablePeerAccess = 28,
//    HIP_API_ID_hipDeviceEnablePeerAccess = 29,
//    HIP_API_ID_hipDeviceGet = 30,
//    HIP_API_ID_hipDeviceGetAttribute = 31,
//    HIP_API_ID_hipDeviceGetByPCIBusId = 32,
//    HIP_API_ID_hipDeviceGetCacheConfig = 33,
//    HIP_API_ID_hipDeviceGetLimit = 34,
//    HIP_API_ID_hipDeviceGetName = 35,
//    HIP_API_ID_hipDeviceGetP2PAttribute = 36,
//    HIP_API_ID_hipDeviceGetPCIBusId = 37,
//    HIP_API_ID_hipDeviceGetSharedMemConfig = 38,
//    HIP_API_ID_hipDeviceGetStreamPriorityRange = 39,
//    HIP_API_ID_hipDevicePrimaryCtxGetState = 40,
//    HIP_API_ID_hipDevicePrimaryCtxRelease = 41,
//    HIP_API_ID_hipDevicePrimaryCtxReset = 42,
//    HIP_API_ID_hipDevicePrimaryCtxRetain = 43,
//    HIP_API_ID_hipDevicePrimaryCtxSetFlags = 44,
//    HIP_API_ID_hipDeviceReset = 45,
//    HIP_API_ID_hipDeviceSetCacheConfig = 46,
//    HIP_API_ID_hipDeviceSetSharedMemConfig = 47,
//    HIP_API_ID_hipDeviceSynchronize = 48,
//    HIP_API_ID_hipDeviceTotalMem = 49,
//    HIP_API_ID_RESERVED_50 = 50,
//    HIP_API_ID_hipDrvMemcpy2DUnaligned = 51,
//    HIP_API_ID_hipDrvMemcpy3D = 52,
//    HIP_API_ID_hipDrvMemcpy3DAsync = 53,
//    HIP_API_ID_hipEventCreate = 54,
//    HIP_API_ID_hipEventCreateWithFlags = 55,
//    HIP_API_ID_hipEventDestroy = 56,
//    HIP_API_ID_hipEventElapsedTime = 57,
//    HIP_API_ID_hipEventQuery = 58,
//    HIP_API_ID_hipEventRecord = 59,
//    HIP_API_ID_hipEventSynchronize = 60,
//    HIP_API_ID_hipExtGetLinkTypeAndHopCount = 61,
//    HIP_API_ID_hipExtLaunchKernel = 62,
//    HIP_API_ID_hipExtLaunchMultiKernelMultiDevice = 63,
//    HIP_API_ID_hipExtMallocWithFlags = 64,
//    HIP_API_ID_hipExtModuleLaunchKernel = 65,
//    HIP_API_ID_hipExtStreamCreateWithCUMask = 66,
//    HIP_API_ID_hipExtStreamGetCUMask = 67,
//    HIP_API_ID_hipExternalMemoryGetMappedBuffer = 68,
//    HIP_API_ID_hipFree = 69,
//    HIP_API_ID_hipFreeArray = 70,
//    HIP_API_ID_hipFreeHost = 71,
//    HIP_API_ID_hipFreeMipmappedArray = 72,
//    HIP_API_ID_hipFuncGetAttribute = 73,
//    HIP_API_ID_hipFuncGetAttributes = 74,
//    HIP_API_ID_hipFuncSetAttribute = 75,
//    HIP_API_ID_hipFuncSetCacheConfig = 76,
//    HIP_API_ID_hipFuncSetSharedMemConfig = 77,
//    HIP_API_ID_hipGetDevice = 78,
//    HIP_API_ID_hipGetDeviceCount = 79,
//    HIP_API_ID_hipGetDeviceFlags = 80,
//    HIP_API_ID_hipGetDeviceProperties = 81,
//    HIP_API_ID_RESERVED_82 = 82,
//    HIP_API_ID_hipGetErrorString = 83,
//    HIP_API_ID_hipGetLastError = 84,
//    HIP_API_ID_hipGetMipmappedArrayLevel = 85,
//    HIP_API_ID_hipGetSymbolAddress = 86,
//    HIP_API_ID_hipGetSymbolSize = 87,
//    HIP_API_ID_hipHccModuleLaunchKernel = 88,
//    HIP_API_ID_hipHostAlloc = 89,
//    HIP_API_ID_hipHostFree = 90,
//    HIP_API_ID_hipHostGetDevicePointer = 91,
//    HIP_API_ID_hipHostGetFlags = 92,
//    HIP_API_ID_hipHostMalloc = 93,
//    HIP_API_ID_hipHostRegister = 94,
//    HIP_API_ID_hipHostUnregister = 95,
//    HIP_API_ID_hipImportExternalMemory = 96,
//    HIP_API_ID_hipImportExternalSemaphore = 97,
//    HIP_API_ID_hipInit = 98,
//    HIP_API_ID_hipIpcCloseMemHandle = 99,
//    HIP_API_ID_hipIpcGetEventHandle = 100,
//    HIP_API_ID_hipIpcGetMemHandle = 101,
//    HIP_API_ID_hipIpcOpenEventHandle = 102,
//    HIP_API_ID_hipIpcOpenMemHandle = 103,
//    HIP_API_ID_hipLaunchByPtr = 104,
//    HIP_API_ID_hipLaunchCooperativeKernel = 105,
//    HIP_API_ID_hipLaunchCooperativeKernelMultiDevice = 106,
//    HIP_API_ID_hipLaunchKernel = 107,
//    HIP_API_ID_hipMalloc = 108,
//    HIP_API_ID_hipMalloc3D = 109,
//    HIP_API_ID_hipMalloc3DArray = 110,
//    HIP_API_ID_hipMallocArray = 111,
//    HIP_API_ID_hipMallocHost = 112,
//    HIP_API_ID_hipMallocManaged = 113,
//    HIP_API_ID_hipMallocMipmappedArray = 114,
//    HIP_API_ID_hipMallocPitch = 115,
//    HIP_API_ID_hipMemAdvise = 116,
//    HIP_API_ID_hipMemAllocHost = 117,
//    HIP_API_ID_hipMemAllocPitch = 118,
//    HIP_API_ID_hipMemGetAddressRange = 119,
//    HIP_API_ID_hipMemGetInfo = 120,
//    HIP_API_ID_hipMemPrefetchAsync = 121,
//    HIP_API_ID_hipMemPtrGetInfo = 122,
//    HIP_API_ID_hipMemRangeGetAttribute = 123,
//    HIP_API_ID_hipMemRangeGetAttributes = 124,
//    HIP_API_ID_hipMemcpy = 125,
//    HIP_API_ID_hipMemcpy2D = 126,
//    HIP_API_ID_hipMemcpy2DAsync = 127,
//    HIP_API_ID_hipMemcpy2DFromArray = 128,
//    HIP_API_ID_hipMemcpy2DFromArrayAsync = 129,
//    HIP_API_ID_hipMemcpy2DToArray = 130,
//    HIP_API_ID_hipMemcpy2DToArrayAsync = 131,
//    HIP_API_ID_hipMemcpy3D = 132,
//    HIP_API_ID_hipMemcpy3DAsync = 133,
//    HIP_API_ID_hipMemcpyAsync = 134,
//    HIP_API_ID_hipMemcpyAtoH = 135,
//    HIP_API_ID_hipMemcpyDtoD = 136,
//    HIP_API_ID_hipMemcpyDtoDAsync = 137,
//    HIP_API_ID_hipMemcpyDtoH = 138,
//    HIP_API_ID_hipMemcpyDtoHAsync = 139,
//    HIP_API_ID_hipMemcpyFromArray = 140,
//    HIP_API_ID_hipMemcpyFromSymbol = 141,
//    HIP_API_ID_hipMemcpyFromSymbolAsync = 142,
//    HIP_API_ID_hipMemcpyHtoA = 143,
//    HIP_API_ID_hipMemcpyHtoD = 144,
//    HIP_API_ID_hipMemcpyHtoDAsync = 145,
//    HIP_API_ID_hipMemcpyParam2D = 146,
//    HIP_API_ID_hipMemcpyParam2DAsync = 147,
//    HIP_API_ID_hipMemcpyPeer = 148,
//    HIP_API_ID_hipMemcpyPeerAsync = 149,
//    HIP_API_ID_hipMemcpyToArray = 150,
//    HIP_API_ID_hipMemcpyToSymbol = 151,
//    HIP_API_ID_hipMemcpyToSymbolAsync = 152,
//    HIP_API_ID_hipMemcpyWithStream = 153,
//    HIP_API_ID_hipMemset = 154,
//    HIP_API_ID_hipMemset2D = 155,
//    HIP_API_ID_hipMemset2DAsync = 156,
//    HIP_API_ID_hipMemset3D = 157,
//    HIP_API_ID_hipMemset3DAsync = 158,
//    HIP_API_ID_hipMemsetAsync = 159,
//    HIP_API_ID_hipMemsetD16 = 160,
//    HIP_API_ID_hipMemsetD16Async = 161,
//    HIP_API_ID_hipMemsetD32 = 162,
//    HIP_API_ID_hipMemsetD32Async = 163,
//    HIP_API_ID_hipMemsetD8 = 164,
//    HIP_API_ID_hipMemsetD8Async = 165,
//    HIP_API_ID_hipModuleGetFunction = 166,
//    HIP_API_ID_hipModuleGetGlobal = 167,
//    HIP_API_ID_hipModuleGetTexRef = 168,
//    HIP_API_ID_hipModuleLaunchKernel = 169,
//    HIP_API_ID_hipModuleLoad = 170,
//    HIP_API_ID_hipModuleLoadData = 171,
//    HIP_API_ID_hipModuleLoadDataEx = 172,
//    HIP_API_ID_hipModuleOccupancyMaxActiveBlocksPerMultiprocessor = 173,
//    HIP_API_ID_hipModuleOccupancyMaxActiveBlocksPerMultiprocessorWithFlags = 174,
//    HIP_API_ID_hipModuleOccupancyMaxPotentialBlockSize = 175,
//    HIP_API_ID_hipModuleOccupancyMaxPotentialBlockSizeWithFlags = 176,
//    HIP_API_ID_hipModuleUnload = 177,
//    HIP_API_ID_hipOccupancyMaxActiveBlocksPerMultiprocessor = 178,
//    HIP_API_ID_hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags = 179,
//    HIP_API_ID_hipOccupancyMaxPotentialBlockSize = 180,
//    HIP_API_ID_hipPeekAtLastError = 181,
//    HIP_API_ID_hipPointerGetAttributes = 182,
//    HIP_API_ID_hipProfilerStart = 183,
//    HIP_API_ID_hipProfilerStop = 184,
//    HIP_API_ID_RESERVED_185 = 185,
//    HIP_API_ID_hipSetDevice = 186,
//    HIP_API_ID_hipSetDeviceFlags = 187,
//    HIP_API_ID_hipSetupArgument = 188,
//    HIP_API_ID_hipSignalExternalSemaphoresAsync = 189,
//    HIP_API_ID_hipStreamAddCallback = 190,
//    HIP_API_ID_hipStreamAttachMemAsync = 191,
//    HIP_API_ID_hipStreamCreate = 192,
//    HIP_API_ID_hipStreamCreateWithFlags = 193,
//    HIP_API_ID_hipStreamCreateWithPriority = 194,
//    HIP_API_ID_hipStreamDestroy = 195,
//    HIP_API_ID_hipStreamGetFlags = 196,
//    HIP_API_ID_hipStreamGetPriority = 197,
//    HIP_API_ID_hipStreamQuery = 198,
//    HIP_API_ID_hipStreamSynchronize = 199,
//    HIP_API_ID_hipStreamWaitEvent = 200,
//    HIP_API_ID_hipStreamWaitValue32 = 201,
//    HIP_API_ID_hipStreamWaitValue64 = 202,
//    HIP_API_ID_hipStreamWriteValue32 = 203,
//    HIP_API_ID_hipStreamWriteValue64 = 204,
//    HIP_API_ID_hipWaitExternalSemaphoresAsync = 205,
//    HIP_API_ID_hipCreateSurfaceObject = 206,
//    HIP_API_ID_hipDestroySurfaceObject = 207,
//    HIP_API_ID_hipGraphAddKernelNode = 208,
//    HIP_API_ID_hipGraphAddMemcpyNode = 209,
//    HIP_API_ID_hipGraphAddMemsetNode = 210,
//    HIP_API_ID_hipGraphCreate = 211,
//    HIP_API_ID_hipGraphDestroy = 212,
//    HIP_API_ID_hipGraphExecDestroy = 213,
//    HIP_API_ID_hipGraphInstantiate = 214,
//    HIP_API_ID_hipGraphLaunch = 215,
//    HIP_API_ID_hipMipmappedArrayCreate = 216,
//    HIP_API_ID_hipMipmappedArrayDestroy = 217,
//    HIP_API_ID_hipMipmappedArrayGetLevel = 218,
//    HIP_API_ID_hipStreamBeginCapture = 219,
//    HIP_API_ID_hipStreamEndCapture = 220,
//    HIP_API_ID_hipTexRefGetAddress = 221,
//    HIP_API_ID_hipTexRefGetFlags = 222,
//    HIP_API_ID_hipTexRefGetFormat = 223,
//    HIP_API_ID_hipTexRefGetMaxAnisotropy = 224,
//    HIP_API_ID_hipTexRefGetMipMappedArray = 225,
//    HIP_API_ID_hipTexRefGetMipmapLevelBias = 226,
//    HIP_API_ID_hipTexRefGetMipmapLevelClamp = 227,
//    HIP_API_ID_hipTexRefSetAddress = 228,
//    HIP_API_ID_hipTexRefSetAddress2D = 229,
//    HIP_API_ID_hipTexRefSetBorderColor = 230,
//    HIP_API_ID_hipTexRefSetFormat = 231,
//    HIP_API_ID_hipTexRefSetMaxAnisotropy = 232,
//    HIP_API_ID_hipTexRefSetMipmapLevelClamp = 233,
//    HIP_API_ID_hipTexRefSetMipmappedArray = 234,
//    HIP_API_ID_hipGLGetDevices = 235,
//    HIP_API_ID_hipGraphAddDependencies = 236,
//    HIP_API_ID_hipGraphAddEmptyNode = 237,
//    HIP_API_ID_hipGraphExecKernelNodeSetParams = 238,
//    HIP_API_ID_hipGraphGetNodes = 239,
//    HIP_API_ID_hipGraphGetRootNodes = 240,
//    HIP_API_ID_hipGraphKernelNodeGetParams = 241,
//    HIP_API_ID_hipGraphKernelNodeSetParams = 242,
//    HIP_API_ID_hipGraphMemcpyNodeGetParams = 243,
//    HIP_API_ID_hipGraphMemcpyNodeSetParams = 244,
//    HIP_API_ID_hipGraphMemsetNodeGetParams = 245,
//    HIP_API_ID_hipGraphMemsetNodeSetParams = 246,
//    HIP_API_ID_hipGraphicsGLRegisterBuffer = 247,
//    HIP_API_ID_hipGraphicsMapResources = 248,
//    HIP_API_ID_hipGraphicsResourceGetMappedPointer = 249,
//    HIP_API_ID_hipGraphicsUnmapResources = 250,
//    HIP_API_ID_hipGraphicsUnregisterResource = 251,
//    HIP_API_ID_hipGraphAddChildGraphNode = 252,
//    HIP_API_ID_hipGraphAddEventRecordNode = 253,
//    HIP_API_ID_hipGraphAddEventWaitNode = 254,
//    HIP_API_ID_hipGraphAddHostNode = 255,
//    HIP_API_ID_hipGraphAddMemcpyNode1D = 256,
//    HIP_API_ID_hipGraphAddMemcpyNodeFromSymbol = 257,
//    HIP_API_ID_hipGraphAddMemcpyNodeToSymbol = 258,
//    HIP_API_ID_hipGraphChildGraphNodeGetGraph = 259,
//    HIP_API_ID_hipGraphClone = 260,
//    HIP_API_ID_hipGraphDestroyNode = 261,
//    HIP_API_ID_hipGraphEventRecordNodeGetEvent = 262,
//    HIP_API_ID_hipGraphEventRecordNodeSetEvent = 263,
//    HIP_API_ID_hipGraphEventWaitNodeGetEvent = 264,
//    HIP_API_ID_hipGraphEventWaitNodeSetEvent = 265,
//    HIP_API_ID_hipGraphExecChildGraphNodeSetParams = 266,
//    HIP_API_ID_hipGraphExecEventRecordNodeSetEvent = 267,
//    HIP_API_ID_hipGraphExecEventWaitNodeSetEvent = 268,
//    HIP_API_ID_hipGraphExecHostNodeSetParams = 269,
//    HIP_API_ID_hipGraphExecMemcpyNodeSetParams = 270,
//    HIP_API_ID_hipGraphExecMemcpyNodeSetParams1D = 271,
//    HIP_API_ID_hipGraphExecMemcpyNodeSetParamsFromSymbol = 272,
//    HIP_API_ID_hipGraphExecMemcpyNodeSetParamsToSymbol = 273,
//    HIP_API_ID_hipGraphExecMemsetNodeSetParams = 274,
//    HIP_API_ID_hipGraphExecUpdate = 275,
//    HIP_API_ID_hipGraphGetEdges = 276,
//    HIP_API_ID_hipGraphHostNodeGetParams = 277,
//    HIP_API_ID_hipGraphHostNodeSetParams = 278,
//    HIP_API_ID_hipGraphInstantiateWithFlags = 279,
//    HIP_API_ID_hipGraphMemcpyNodeSetParams1D = 280,
//    HIP_API_ID_hipGraphMemcpyNodeSetParamsFromSymbol = 281,
//    HIP_API_ID_hipGraphMemcpyNodeSetParamsToSymbol = 282,
//    HIP_API_ID_hipGraphNodeFindInClone = 283,
//    HIP_API_ID_hipGraphNodeGetDependencies = 284,
//    HIP_API_ID_hipGraphNodeGetDependentNodes = 285,
//    HIP_API_ID_hipGraphNodeGetType = 286,
//    HIP_API_ID_hipGraphRemoveDependencies = 287,
//    HIP_API_ID_hipStreamGetCaptureInfo = 288,
//    HIP_API_ID_hipStreamGetCaptureInfo_v2 = 289,
//    HIP_API_ID_hipStreamIsCapturing = 290,
//    HIP_API_ID_hipStreamUpdateCaptureDependencies = 291,
//    HIP_API_ID_hipDrvPointerGetAttributes = 292,
//    HIP_API_ID_hipGraphicsGLRegisterImage = 293,
//    HIP_API_ID_hipGraphicsSubResourceGetMappedArray = 294,
//    HIP_API_ID_hipPointerGetAttribute = 295,
//    HIP_API_ID_RESERVED_296 = 296,
//    HIP_API_ID_hipThreadExchangeStreamCaptureMode = 297,
//    HIP_API_ID_hipDeviceGetUuid = 298,
//    HIP_API_ID_hipGetChannelDesc = 299,
//    HIP_API_ID_hipGraphKernelNodeGetAttribute = 300,
//    HIP_API_ID_hipGraphKernelNodeSetAttribute = 301,
//    HIP_API_ID_hipLaunchHostFunc = 302,
//    HIP_API_ID_hipDeviceGetDefaultMemPool = 303,
//    HIP_API_ID_hipDeviceGetMemPool = 304,
//    HIP_API_ID_hipDeviceSetMemPool = 305,
//    HIP_API_ID_hipFreeAsync = 306,
//    HIP_API_ID_hipMallocAsync = 307,
//    HIP_API_ID_hipMallocFromPoolAsync = 308,
//    HIP_API_ID_hipMemPoolCreate = 309,
//    HIP_API_ID_hipMemPoolDestroy = 310,
//    HIP_API_ID_hipMemPoolExportPointer = 311,
//    HIP_API_ID_hipMemPoolExportToShareableHandle = 312,
//    HIP_API_ID_hipMemPoolGetAccess = 313,
//    HIP_API_ID_hipMemPoolGetAttribute = 314,
//    HIP_API_ID_hipMemPoolImportFromShareableHandle = 315,
//    HIP_API_ID_hipMemPoolImportPointer = 316,
//    HIP_API_ID_hipMemPoolSetAccess = 317,
//    HIP_API_ID_hipMemPoolSetAttribute = 318,
//    HIP_API_ID_hipMemPoolTrimTo = 319,
//    HIP_API_ID_hipMemAddressFree = 320,
//    HIP_API_ID_hipMemAddressReserve = 321,
//    HIP_API_ID_hipMemCreate = 322,
//    HIP_API_ID_hipMemExportToShareableHandle = 323,
//    HIP_API_ID_hipMemGetAccess = 324,
//    HIP_API_ID_hipMemGetAllocationGranularity = 325,
//    HIP_API_ID_hipMemGetAllocationPropertiesFromHandle = 326,
//    HIP_API_ID_hipMemImportFromShareableHandle = 327,
//    HIP_API_ID_hipMemMap = 328,
//    HIP_API_ID_hipMemMapArrayAsync = 329,
//    HIP_API_ID_hipMemRelease = 330,
//    HIP_API_ID_hipMemRetainAllocationHandle = 331,
//    HIP_API_ID_hipMemSetAccess = 332,
//    HIP_API_ID_hipMemUnmap = 333,
//    HIP_API_ID_hipDeviceSetGraphMemAttribute = 334,
//    HIP_API_ID_hipDeviceGetGraphMemAttribute = 335,
//    HIP_API_ID_hipDeviceGraphMemTrim = 336,
//    HIP_API_ID_hipDeviceSetLimit = 337,
//    HIP_API_ID_hipTexRefSetArray = 338,
//    HIP_API_ID_hipTexRefSetFlags = 339,
//    HIP_API_ID_hipTexRefSetMipmapLevelBias = 340,
//    HIP_API_ID_hipDriverGetVersion = 341,
//    HIP_API_ID_hipGraphUpload = 342,
//    HIP_API_ID_hipRuntimeGetVersion = 343,
//    HIP_API_ID_hipUserObjectCreate = 344,
//    HIP_API_ID_hipUserObjectRelease = 345,
//    HIP_API_ID_hipUserObjectRetain = 346,
//    HIP_API_ID_hipGraphRetainUserObject = 347,
//    HIP_API_ID_hipGraphReleaseUserObject = 348,
//    HIP_API_ID_LAST = 348,
