# Turns the assembled test kernels into a C++ source the harness can link.
#
# Run in script mode at build time, once the per-architecture .bin files exist:
#
#   cmake -DARCHS="gfx908;gfx90a" -DBINDIR=<dir> -DOUT=<file.cpp>
#         -P EmbedTestKernels.cmake
#
# Embedding rather than loading a file at runtime keeps the suite a single
# binary with nothing to locate at run time, which matters because it has to be
# easy for someone else to run on their own hardware.

if(NOT DEFINED ARCHS OR NOT DEFINED BINDIR OR NOT DEFINED OUT)
    message(FATAL_ERROR "EmbedTestKernels.cmake needs ARCHS, BINDIR and OUT")
endif()

set(BODY "")
string(APPEND BODY "// Generated by EmbedTestKernels.cmake -- do not edit.\n")
string(APPEND BODY "//\n")
string(APPEND BODY "// Machine code for the test kernel, one array per GPU architecture the\n")
string(APPEND BODY "// build targeted. Assembled from TestKernel.s by ROCm's clang.\n\n")
string(APPEND BODY "#include \"AqlTestQueue.h\"\n\n")
string(APPEND BODY "namespace luthier::test::kfd {\nnamespace {\n\n")

foreach(ARCH IN LISTS ARCHS)
    set(BIN "${BINDIR}/TestKernel_${ARCH}.bin")
    if(NOT EXISTS "${BIN}")
        message(FATAL_ERROR "missing assembled kernel: ${BIN}")
    endif()

    file(READ "${BIN}" HEXDATA HEX)
    string(REGEX REPLACE "(..)" "0x\\1," BYTES "${HEXDATA}")
    string(REGEX REPLACE ",$" "" BYTES "${BYTES}")

    # A safe C++ identifier: gfx908 -> Code_gfx908, gfx10-3-generic -> underscores
    string(MAKE_C_IDENTIFIER "${ARCH}" IDENT)
    string(APPEND BODY "const unsigned char Code_${IDENT}[] = {${BYTES}};\n")
endforeach()

string(APPEND BODY "\n} // namespace\n\n")
string(APPEND BODY "std::vector<uint8_t> testKernelCodeFor(const std::string &GfxArch) {\n")

foreach(ARCH IN LISTS ARCHS)
    string(MAKE_C_IDENTIFIER "${ARCH}" IDENT)
    string(APPEND BODY "  if (GfxArch == \"${ARCH}\")\n")
    string(APPEND BODY "    return {std::begin(Code_${IDENT}), std::end(Code_${IDENT})};\n")
endforeach()

# An empty result is how the harness learns to skip with a clear message rather
# than failing in a way that looks like a wrapper bug.
string(APPEND BODY "  return {};\n")
string(APPEND BODY "}\n\n")
string(APPEND BODY "} // namespace luthier::test::kfd\n")

file(WRITE "${OUT}" "${BODY}")
message(STATUS "Embedded KFD test kernels for: ${ARCHS}")
