//===-- GotchaAbi.h - the part of GOTCHA's ABI Luthier uses -----*- C++ -*-===//
// Copyright @ Northeastern University Computer Architecture Lab
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//
///
/// \file
/// Luthier's own declaration of the three GOTCHA entry points it calls.
///
/// \par Why declared here instead of fetched or vendored
/// GOTCHA arrives as \c libgotcha.so.3 inside rocprofiler-sdk's private library
/// directory, and that package ships \b no headers. Two alternatives were
/// considered and rejected:
/// \li Fetching upstream's headers pins a GOTCHA version that need not match the
///     shared object actually installed, and the mismatch is silent -- a changed
///     \c gotcha_binding_t layout would corrupt a struct rather than fail to
///     compile. GOTCHA's \c gotcha_config.h is also generated by its own build, so
///     a fetch needs a hand-written stub regardless.
/// \li Copying the headers in puts LGPL 2.1 files inside an Apache 2.0 repository.
///
/// Declaring the four types and three functions we use avoids both: a mismatch
/// becomes a link error, and no GOTCHA text is copied. Dynamically linking an LGPL
/// library is the arrangement LGPL exists to permit.
///
/// \par Pinned to SONAME libgotcha.so.3
/// Verified against ROCm 7.2.4, which exports \c gotcha_wrap,
/// \c gotcha_set_priority, \c gotcha_get_priority, \c gotcha_get_wrappee,
/// \c gotcha_init and the four library-filter functions as global symbols. If a
/// future ROCm ships SONAME 4, revisit this file rather than assuming.
///
/// \note \c gotcha_init is exported but is not part of GOTCHA's documented
/// interface, and is deliberately not declared here. libgotcha is a \c DT_NEEDED
/// dependency of the library that includes this header, so its own initialisation
/// runs before ours.
//===----------------------------------------------------------------------===//
#ifndef LUTHIER_KFD_GOTCHA_ABI_H
#define LUTHIER_KFD_GOTCHA_ABI_H

#include <cstddef>

extern "C" {

/// Opaque handle GOTCHA fills in for a wrapped symbol. It is the slot GOTCHA
/// re-points when another tool inserts itself inside ours, which is why the value
/// behind it must be read per call rather than stored.
using gotcha_wrappee_handle_t = void *;

/// One symbol to wrap. Field order is GOTCHA's, not ours.
struct gotcha_binding_t {
  const char *name;
  void *wrapper_pointer;
  gotcha_wrappee_handle_t *function_handle;
};

enum gotcha_error_t {
  GOTCHA_SUCCESS = 0,
  GOTCHA_FUNCTION_NOT_FOUND,
  GOTCHA_INTERNAL,
  GOTCHA_INVALID_TOOL
};

/// Rewrite the lookup tables of the loaded objects so \c name resolves to
/// \c wrapper_pointer, and store the displaced function in \c function_handle.
gotcha_error_t gotcha_wrap(gotcha_binding_t *Bindings, int NumActions,
                           const char *ToolName);

/// Place a tool in an existing chain. GOTCHA's rule: lower values are called
/// innermost, so a higher priority sits closer to the application.
gotcha_error_t gotcha_set_priority(const char *ToolName, int Priority);

/// The function this tool displaced -- the next link inward.
void *gotcha_get_wrappee(gotcha_wrappee_handle_t Handle);

} // extern "C"

// Three pointers, in this order. A layout change would otherwise be silent.
static_assert(sizeof(gotcha_binding_t) == 3 * sizeof(void *),
              "gotcha_binding_t does not match libgotcha.so.3's layout");
static_assert(offsetof(gotcha_binding_t, name) == 0,
              "gotcha_binding_t::name moved");
static_assert(offsetof(gotcha_binding_t, wrapper_pointer) == sizeof(void *),
              "gotcha_binding_t::wrapper_pointer moved");
static_assert(offsetof(gotcha_binding_t, function_handle) == 2 * sizeof(void *),
              "gotcha_binding_t::function_handle moved");

#endif // LUTHIER_KFD_GOTCHA_ABI_H
