// NOLINTBEGIN
/* Generated by hip_intercept_gen.py. DO NOT EDIT! */
#include "hip_compiler_intercept.hpp"
#include "luthier/types.h"
#include <rocprofiler-sdk/hip/api_args.h>
#include <rocprofiler-sdk/hip/api_id.h>

rocprofiler_dim3_t convertToRocprofilerDim3(const dim3& d) {
    return rocprofiler_dim3_t{d.x, d.y, d.z};
}

static hipError_t __hipPopCallConfiguration_callback(dim3* gridDim, dim3* blockDim, size_t* sharedMem, hipStream_t* stream) {
  auto& HipInterceptor = luthier::hip::CompilerInterceptor::instance();
  auto ApiId = ROCPROFILER_HIP_COMPILER_API_ID___hipPopCallConfiguration;
  bool IsUserCallbackEnabled = HipInterceptor.isUserCallbackEnabled(ApiId);
  bool IsInternalCallbackEnabled = HipInterceptor.isInternalCallbackEnabled(ApiId);
  bool ShouldCallback = IsUserCallbackEnabled || IsInternalCallbackEnabled;
  if (ShouldCallback) {
    hipError_t Out{};
    auto& HipUserCallback = HipInterceptor.getUserCallback();
    auto& HipInternalCallback = HipInterceptor.getInternalCallback();
    rocprofiler_hip_api_args_t Args;
    bool SkipFunction{false};
    Args.__hipPopCallConfiguration.gridDim = gridDim;
    Args.__hipPopCallConfiguration.blockDim = blockDim;
    Args.__hipPopCallConfiguration.sharedMem = sharedMem;
    Args.__hipPopCallConfiguration.stream = stream;
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId, &SkipFunction);
    if (!SkipFunction)
      Out = HipInterceptor.getSavedCompilerTable().__hipPopCallConfiguration_fn(Args.__hipPopCallConfiguration.gridDim, Args.__hipPopCallConfiguration.blockDim, Args.__hipPopCallConfiguration.sharedMem, Args.__hipPopCallConfiguration.stream);
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId, &SkipFunction);
    return Out;
  }
  else {
    return HipInterceptor.getSavedCompilerTable().__hipPopCallConfiguration_fn(gridDim, blockDim, sharedMem, stream);
  }
}

static hipError_t __hipPushCallConfiguration_callback(dim3 gridDim, dim3 blockDim, size_t sharedMem, hipStream_t stream) {
  auto& HipInterceptor = luthier::hip::CompilerInterceptor::instance();
  auto ApiId = ROCPROFILER_HIP_COMPILER_API_ID___hipPushCallConfiguration;
  bool IsUserCallbackEnabled = HipInterceptor.isUserCallbackEnabled(ApiId);
  bool IsInternalCallbackEnabled = HipInterceptor.isInternalCallbackEnabled(ApiId);
  bool ShouldCallback = IsUserCallbackEnabled || IsInternalCallbackEnabled;
  if (ShouldCallback) {
    hipError_t Out{};
    auto& HipUserCallback = HipInterceptor.getUserCallback();
    auto& HipInternalCallback = HipInterceptor.getInternalCallback();
    rocprofiler_hip_api_args_t Args;
    bool SkipFunction{false};
    Args.__hipPushCallConfiguration.gridDim = convertToRocprofilerDim3(gridDim);
    Args.__hipPushCallConfiguration.blockDim = convertToRocprofilerDim3(blockDim);
    Args.__hipPushCallConfiguration.sharedMem = sharedMem;
    Args.__hipPushCallConfiguration.stream = stream;
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId, &SkipFunction);
    if (!SkipFunction)
      Out = HipInterceptor.getSavedCompilerTable().__hipPushCallConfiguration_fn(gridDim, blockDim, Args.__hipPushCallConfiguration.sharedMem, Args.__hipPushCallConfiguration.stream);
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId, &SkipFunction);
    return Out;
  }
  else {
    return HipInterceptor.getSavedCompilerTable().__hipPushCallConfiguration_fn(gridDim, blockDim, sharedMem, stream);
  }
}

static void** __hipRegisterFatBinary_callback(const void* data) {
  auto& HipInterceptor = luthier::hip::CompilerInterceptor::instance();
  auto ApiId = ROCPROFILER_HIP_COMPILER_API_ID___hipRegisterFatBinary;
  bool IsUserCallbackEnabled = HipInterceptor.isUserCallbackEnabled(ApiId);
  bool IsInternalCallbackEnabled = HipInterceptor.isInternalCallbackEnabled(ApiId);
  bool ShouldCallback = IsUserCallbackEnabled || IsInternalCallbackEnabled;
  if (ShouldCallback) {
    void** Out{};
    auto& HipUserCallback = HipInterceptor.getUserCallback();
    auto& HipInternalCallback = HipInterceptor.getInternalCallback();
    rocprofiler_hip_api_args_t Args;
    bool SkipFunction{false};
    Args.__hipRegisterFatBinary.data = data;
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId, &SkipFunction);
    if (!SkipFunction)
      Out = HipInterceptor.getSavedCompilerTable().__hipRegisterFatBinary_fn(Args.__hipRegisterFatBinary.data);
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId, &SkipFunction);
    return Out;
  }
  else {
    return HipInterceptor.getSavedCompilerTable().__hipRegisterFatBinary_fn(data);
  }
}

static void __hipRegisterFunction_callback(void** modules, const void* hostFunction, char* deviceFunction, const char* deviceName, unsigned int threadLimit, uint3* tid, uint3* bid, dim3* blockDim, dim3* gridDim, int* wSize) {
  auto& HipInterceptor = luthier::hip::CompilerInterceptor::instance();
  auto ApiId = ROCPROFILER_HIP_COMPILER_API_ID___hipRegisterFunction;
  bool IsUserCallbackEnabled = HipInterceptor.isUserCallbackEnabled(ApiId);
  bool IsInternalCallbackEnabled = HipInterceptor.isInternalCallbackEnabled(ApiId);
  bool ShouldCallback = IsUserCallbackEnabled || IsInternalCallbackEnabled;
  if (ShouldCallback) {
    auto& HipUserCallback = HipInterceptor.getUserCallback();
    auto& HipInternalCallback = HipInterceptor.getInternalCallback();
    rocprofiler_hip_api_args_t Args;
    bool SkipFunction{false};
    Args.__hipRegisterFunction.modules = modules;
    Args.__hipRegisterFunction.hostFunction = hostFunction;
    Args.__hipRegisterFunction.deviceFunction = deviceFunction;
    Args.__hipRegisterFunction.deviceName = deviceName;
    Args.__hipRegisterFunction.threadLimit = threadLimit;
    Args.__hipRegisterFunction.tid = tid;
    Args.__hipRegisterFunction.bid = bid;
    Args.__hipRegisterFunction.blockDim = blockDim;
    Args.__hipRegisterFunction.gridDim = gridDim;
    Args.__hipRegisterFunction.wSize = wSize;
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId, &SkipFunction);
    if (!SkipFunction)
       HipInterceptor.getSavedCompilerTable().__hipRegisterFunction_fn(Args.__hipRegisterFunction.modules, Args.__hipRegisterFunction.hostFunction, Args.__hipRegisterFunction.deviceFunction, Args.__hipRegisterFunction.deviceName, Args.__hipRegisterFunction.threadLimit, Args.__hipRegisterFunction.tid, Args.__hipRegisterFunction.bid, Args.__hipRegisterFunction.blockDim, Args.__hipRegisterFunction.gridDim, Args.__hipRegisterFunction.wSize);
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId, &SkipFunction);
    
  }
  else {
    return HipInterceptor.getSavedCompilerTable().__hipRegisterFunction_fn(modules, hostFunction, deviceFunction, deviceName, threadLimit, tid, bid, blockDim, gridDim, wSize);
  }
}

static void __hipRegisterManagedVar_callback(void* hipModule, void** pointer, void* init_value, const char* name, size_t size, unsigned align) {
  auto& HipInterceptor = luthier::hip::CompilerInterceptor::instance();
  auto ApiId = ROCPROFILER_HIP_COMPILER_API_ID___hipRegisterManagedVar;
  bool IsUserCallbackEnabled = HipInterceptor.isUserCallbackEnabled(ApiId);
  bool IsInternalCallbackEnabled = HipInterceptor.isInternalCallbackEnabled(ApiId);
  bool ShouldCallback = IsUserCallbackEnabled || IsInternalCallbackEnabled;
  if (ShouldCallback) {
    auto& HipUserCallback = HipInterceptor.getUserCallback();
    auto& HipInternalCallback = HipInterceptor.getInternalCallback();
    rocprofiler_hip_api_args_t Args;
    bool SkipFunction{false};
    Args.__hipRegisterManagedVar.hipModule = hipModule;
    Args.__hipRegisterManagedVar.pointer = pointer;
    Args.__hipRegisterManagedVar.init_value = init_value;
    Args.__hipRegisterManagedVar.name = name;
    Args.__hipRegisterManagedVar.size = size;
    Args.__hipRegisterManagedVar.align = align;
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId, &SkipFunction);
    if (!SkipFunction)
       HipInterceptor.getSavedCompilerTable().__hipRegisterManagedVar_fn(Args.__hipRegisterManagedVar.hipModule, Args.__hipRegisterManagedVar.pointer, Args.__hipRegisterManagedVar.init_value, Args.__hipRegisterManagedVar.name, Args.__hipRegisterManagedVar.size, Args.__hipRegisterManagedVar.align);
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId, &SkipFunction);
    
  }
  else {
    return HipInterceptor.getSavedCompilerTable().__hipRegisterManagedVar_fn(hipModule, pointer, init_value, name, size, align);
  }
}

static void __hipRegisterSurface_callback(void** modules, void* var, char* hostVar, char* deviceVar, int type, int ext) {
  auto& HipInterceptor = luthier::hip::CompilerInterceptor::instance();
  auto ApiId = ROCPROFILER_HIP_COMPILER_API_ID___hipRegisterSurface;
  bool IsUserCallbackEnabled = HipInterceptor.isUserCallbackEnabled(ApiId);
  bool IsInternalCallbackEnabled = HipInterceptor.isInternalCallbackEnabled(ApiId);
  bool ShouldCallback = IsUserCallbackEnabled || IsInternalCallbackEnabled;
  if (ShouldCallback) {
    auto& HipUserCallback = HipInterceptor.getUserCallback();
    auto& HipInternalCallback = HipInterceptor.getInternalCallback();
    rocprofiler_hip_api_args_t Args;
    bool SkipFunction{false};
    Args.__hipRegisterSurface.modules = modules;
    Args.__hipRegisterSurface.var = var;
    Args.__hipRegisterSurface.hostVar = hostVar;
    Args.__hipRegisterSurface.deviceVar = deviceVar;
    Args.__hipRegisterSurface.type = type;
    Args.__hipRegisterSurface.ext = ext;
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId, &SkipFunction);
    if (!SkipFunction)
       HipInterceptor.getSavedCompilerTable().__hipRegisterSurface_fn(Args.__hipRegisterSurface.modules, Args.__hipRegisterSurface.var, Args.__hipRegisterSurface.hostVar, Args.__hipRegisterSurface.deviceVar, Args.__hipRegisterSurface.type, Args.__hipRegisterSurface.ext);
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId, &SkipFunction);
    
  }
  else {
    return HipInterceptor.getSavedCompilerTable().__hipRegisterSurface_fn(modules, var, hostVar, deviceVar, type, ext);
  }
}

static void __hipRegisterTexture_callback(void** modules, void* var, char* hostVar, char* deviceVar, int type, int norm, int ext) {
  auto& HipInterceptor = luthier::hip::CompilerInterceptor::instance();
  auto ApiId = ROCPROFILER_HIP_COMPILER_API_ID___hipRegisterTexture;
  bool IsUserCallbackEnabled = HipInterceptor.isUserCallbackEnabled(ApiId);
  bool IsInternalCallbackEnabled = HipInterceptor.isInternalCallbackEnabled(ApiId);
  bool ShouldCallback = IsUserCallbackEnabled || IsInternalCallbackEnabled;
  if (ShouldCallback) {
    auto& HipUserCallback = HipInterceptor.getUserCallback();
    auto& HipInternalCallback = HipInterceptor.getInternalCallback();
    rocprofiler_hip_api_args_t Args;
    bool SkipFunction{false};
    Args.__hipRegisterTexture.modules = modules;
    Args.__hipRegisterTexture.var = var;
    Args.__hipRegisterTexture.hostVar = hostVar;
    Args.__hipRegisterTexture.deviceVar = deviceVar;
    Args.__hipRegisterTexture.type = type;
    Args.__hipRegisterTexture.norm = norm;
    Args.__hipRegisterTexture.ext = ext;
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId, &SkipFunction);
    if (!SkipFunction)
       HipInterceptor.getSavedCompilerTable().__hipRegisterTexture_fn(Args.__hipRegisterTexture.modules, Args.__hipRegisterTexture.var, Args.__hipRegisterTexture.hostVar, Args.__hipRegisterTexture.deviceVar, Args.__hipRegisterTexture.type, Args.__hipRegisterTexture.norm, Args.__hipRegisterTexture.ext);
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId, &SkipFunction);
    
  }
  else {
    return HipInterceptor.getSavedCompilerTable().__hipRegisterTexture_fn(modules, var, hostVar, deviceVar, type, norm, ext);
  }
}

static void __hipRegisterVar_callback(void** modules, void* var, char* hostVar, char* deviceVar, int ext, size_t size, int constant, int global) {
  auto& HipInterceptor = luthier::hip::CompilerInterceptor::instance();
  auto ApiId = ROCPROFILER_HIP_COMPILER_API_ID___hipRegisterVar;
  bool IsUserCallbackEnabled = HipInterceptor.isUserCallbackEnabled(ApiId);
  bool IsInternalCallbackEnabled = HipInterceptor.isInternalCallbackEnabled(ApiId);
  bool ShouldCallback = IsUserCallbackEnabled || IsInternalCallbackEnabled;
  if (ShouldCallback) {
    auto& HipUserCallback = HipInterceptor.getUserCallback();
    auto& HipInternalCallback = HipInterceptor.getInternalCallback();
    rocprofiler_hip_api_args_t Args;
    bool SkipFunction{false};
    Args.__hipRegisterVar.modules = modules;
    Args.__hipRegisterVar.var = var;
    Args.__hipRegisterVar.hostVar = hostVar;
    Args.__hipRegisterVar.deviceVar = deviceVar;
    Args.__hipRegisterVar.ext = ext;
    Args.__hipRegisterVar.size = size;
    Args.__hipRegisterVar.constant = constant;
    Args.__hipRegisterVar.global = global;
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId, &SkipFunction);
    if (!SkipFunction)
       HipInterceptor.getSavedCompilerTable().__hipRegisterVar_fn(Args.__hipRegisterVar.modules, Args.__hipRegisterVar.var, Args.__hipRegisterVar.hostVar, Args.__hipRegisterVar.deviceVar, Args.__hipRegisterVar.ext, Args.__hipRegisterVar.size, Args.__hipRegisterVar.constant, Args.__hipRegisterVar.global);
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId, &SkipFunction);
    
  }
  else {
    return HipInterceptor.getSavedCompilerTable().__hipRegisterVar_fn(modules, var, hostVar, deviceVar, ext, size, constant, global);
  }
}

static void __hipUnregisterFatBinary_callback(void** modules) {
  auto& HipInterceptor = luthier::hip::CompilerInterceptor::instance();
  auto ApiId = ROCPROFILER_HIP_COMPILER_API_ID___hipUnregisterFatBinary;
  bool IsUserCallbackEnabled = HipInterceptor.isUserCallbackEnabled(ApiId);
  bool IsInternalCallbackEnabled = HipInterceptor.isInternalCallbackEnabled(ApiId);
  bool ShouldCallback = IsUserCallbackEnabled || IsInternalCallbackEnabled;
  if (ShouldCallback) {
    auto& HipUserCallback = HipInterceptor.getUserCallback();
    auto& HipInternalCallback = HipInterceptor.getInternalCallback();
    rocprofiler_hip_api_args_t Args;
    bool SkipFunction{false};
    Args.__hipUnregisterFatBinary.modules = modules;
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_ENTER, ApiId, &SkipFunction);
    if (!SkipFunction)
       HipInterceptor.getSavedCompilerTable().__hipUnregisterFatBinary_fn(Args.__hipUnregisterFatBinary.modules);
    if (IsUserCallbackEnabled)
      HipUserCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId);
    if (IsInternalCallbackEnabled)
      HipInternalCallback(&Args, luthier::API_EVT_PHASE_EXIT, ApiId, &SkipFunction);
    
  }
  else {
    return HipInterceptor.getSavedCompilerTable().__hipUnregisterFatBinary_fn(modules);
  }
}


void luthier::hip::CompilerInterceptor::captureCompilerDispatchTable(HipCompilerDispatchTable *CompilerTable) {
	SavedCompilerDispatchTable = *CompilerTable;
	CompilerTable->__hipPopCallConfiguration_fn = __hipPopCallConfiguration_callback;
	CompilerTable->__hipPushCallConfiguration_fn = __hipPushCallConfiguration_callback;
	CompilerTable->__hipRegisterFatBinary_fn = __hipRegisterFatBinary_callback;
	CompilerTable->__hipRegisterFunction_fn = __hipRegisterFunction_callback;
	CompilerTable->__hipRegisterManagedVar_fn = __hipRegisterManagedVar_callback;
	CompilerTable->__hipRegisterSurface_fn = __hipRegisterSurface_callback;
	CompilerTable->__hipRegisterTexture_fn = __hipRegisterTexture_callback;
	CompilerTable->__hipRegisterVar_fn = __hipRegisterVar_callback;
	CompilerTable->__hipUnregisterFatBinary_fn = __hipUnregisterFatBinary_callback;
};

// NOLINTEND
